{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lightdash.fullname" . }}
  labels:
    {{- include "lightdash.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ default "MISSING" $value | b64enc | quote }}
{{- end }}
{{- end}}

