apiVersion: v2
name: lightdash
description: A Helm chart to deploy lightdash on kubernetes
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.7.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 0.1121.0

maintainers:
  - name: owlas
    email: oliver@lightdash.com
    url: https://github.com/owlas
  - name: jim80net
    email: jim@ramtank.com
    url: https://github.com/jim80net
icon: https://docs.lightdash.com/img/logo.png
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: postgresql.enabled
    version: 11.x.x
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
  - name: browserless-chrome
    version: 0.0.4
    repository: https://charts.sagikazarmark.dev
    condition: browserless-chrome.enabled
