apiVersion: v2
appVersion: 0.27.1
name: lightdash
description: A Helm chart to deploy lightdash on kubernetes
type: application
version: 0.2.1
maintainers:
  - name: jim80net
    email: jim@ramtank.com
    url: https://github.com/jim80net
  - name: aboutphilippe
    email: philippe@restack.io
    url: https://github.com/aboutphilippe
icon: https://docs.lightdash.com/img/logo.png
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: postgresql.enabled
    name: postgresql
    version: 11.x.x
    repository: https://charts.bitnami.com/bitnami
